[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "model"
version = "0.0.0"

[dependencies]
anyhow = "1.0"
rng = {path = "../rng"}
serde = {version = "1.0", features = ["derive"]}
terminal = {path = "../terminal"}
tincture = "1.0.0"
