[package]
edition = "2021"
license = "BlueOak-1.0.0"
name = "model"
version = "0.0.0"

[dependencies]
anyhow = "1.0.70"
rng = {path = "../rng"}
serde = {version = "1.0.159", features = ["derive"]}
terminal = {path = "../terminal"}
tincture = "1.0.0"
