name: CI

on:
  pull_request:
  push:
    branches: master
    paths:
      - "**.rs"
      - "**.toml"
      - "**.lock"
      - "**.yaml"

env:
  RUSTFLAGS: "--deny warnings --warn unreachable-pub"

jobs:
  rust:
    name: Rust

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Load Rust/Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --all-targets --all-features --locked

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Test
        run: cargo test --all-targets --all-features --locked

  fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt -- --check
